hparams:
  gridsearch_trial_no: ${range:0,100}        # used just to repeat same experiment multiple times
  params_set_title: "random"
  use_separate_models_for_each_experiment: True
  model_params:
    eps_last_pipeline_cycle: 1      # could be -1 but current cache has 1 so let it be
    eps_last_episode: ${hparams.num_episodes}       # use -1 when episode counting for eps is disabled
    eps_last_trial: -1  # 10       # use -1 when trials counting for eps is disabled
    eps_last_frame: ${hparams.env_params.num_iters}       # use -1 when iteration counting for eps is disabled
  trial_length: -1 # 10
  num_pipeline_cycles: 0
  num_episodes: 0  # how long to train. # TODO: move num_episodes to model_params
  test_episodes: 10  # will be added to train episodes
  env_params:
    num_iters: [300, 400] # duration of a single episode. NB! warm_start_steps will be subtracted from this value
    map_max: [7, 9]
    map_width: ${hparams.env_params.map_max}   # NB! here it is exclusive max, used for Gridworld environments. Also, this width includes the walls at the border of the game, so 2 units of walls. Therefore, interior is map_width - 2.
    map_height: ${hparams.env_params.map_max}   # NB! here it is exclusive max, used for Gridworld environments. Also, this width includes the walls at the border of the game, so 2 units of walls. Therefore, interior is map_height - 2.
    #
    # to make whole map visible while still agent-centric, set the value to 
    # "max(map_width, map_height) - 3" in case of using Gridworld environments. This is because the map width and height includes walls. The agent always sees its own tile, so the actual radius will be one bigger. Therefore in total 3 units can be substracted.
    render_agent_radius: ${minus_3:${hparams.env_params.map_max}}  
